### ISSUE TITLE
implement max micro optimization

### ISSUE THREAD

**Issue by AndyOGo** [AndyOGo/babel-plugin-math#1]
Transform any `Math.max(...)` to a ternary conditional expression `x > y ? x : y`.

**Todo:**
- [x] any number of arguments shall work, i.e.:
   ```js
   Math.max(1, 2, 3);
   // ->
   (foo = 1 > 2 ? 1 : 2) > 3 ? foo : 3
   ```
- [x] dot `Math.max()` and bracket `Math['max']()` notation should be transformed - https://github.com/babel/babylon/blob/master/ast/spec.md#memberexpression
- [ ] dynamic apply `Math.max.apply(Math, [5,20,50,35])` and call `Math.max.call(Math, 5,20,50,35)`
   ```js
   var arr = [5,20,50,35];
   for(var i=1, l=arr.length, max=arr[0]; i<l; i++) {
     if(arr[i]>max) {
       max=arr[i]
     }
   }
   ```
   http://jsben.ch/srGJl
- [ ] ES6 `...` spread array `Math.max(...args)`
- [ ] cached `const { max } = Math`, `const max = Math.max`, etc. should be transformed too (and the cached variable could be removed)
- [x] derived arguments, like function calls, binary and logical operations shall work
- [x] derived arguments be computed only once

Test Page:
https://astexplorer.net/#/gist/a094859432a2424927d0551f4d037ef8/2dc2ca279a17e3e20beb31627e789f97cc8602af

**Comment by AndyOGo** [comment]
```js
export default function(babel) {
  const { types: t } = babel;
  let hit = 0;

  function isMathCall(node, methodName) {
    if (
      !methodName ||
      !t.isCallExpression(node) ||
      !t.isMemberExpression(node.callee) ||
      !t.isIdentifier(node.callee.object, { name: "Math" }) ||
      (!t.isIdentifier(node.callee.property, { name: methodName }) &&
        !t.isStringLiteral(node.callee.property, { value: methodName }))
    ) {
      return false;
    }

    return true;
  }

  function isSimple(node) {
    return t.isLiteral(node) || t.isIdentifier(node);
  }

  return {
    name: "ast-transform", // not required
    visitor: {
      CallExpression(path) {
        const { node } = path;

        if (!isMathCall(node, "max")) {
          return;
        }

        hit++;

        const { arguments: args } = node;
        const { length } = args;
        const isNested = length > 2;
        let lastIntermmediate;
        let finalmax;
        let lastTernary;
        let lastResult;
        const cache = t.variableDeclaration("var", []);
        const { declarations } = cache;

        for (let index = 1; index < length; index++) {
          const isLast = index === length - 1;
          let result;

          // result of ternary needs to be cached
          if (isNested && !isLast) {
            result = t.identifier(`__max_${hit}_ResultCache_${index}`);

            declarations.push(t.variableDeclarator(result));
          }

          const leftIndex = index - 1;
          const rightIndex = index;
          let leftArg = args[leftIndex];
          let rightArg = args[rightIndex];
          const isLeftSimple = isSimple(leftArg);
          const isRightSimple = isSimple(rightArg);

          // after first run, reuse previous comparison
          if (lastIntermmediate) {
            leftArg = lastIntermmediate;
          } else if (!isLeftSimple) {
            // needs caching if not simple variable or literal
            const leftId = t.identifier(`__max_${hit}_LeftCache_${leftIndex}`);

            declarations.push(t.variableDeclarator(leftId, leftArg));

            leftArg = leftId;
          }

          // needs caching if not simple variable or literal
          if (!isRightSimple) {
            const rightId = t.identifier(`__max_${hit}_RightCache_${leftIndex}`);

            declarations.push(t.variableDeclarator(rightId, rightArg));

            rightArg = rightId;
          }

          // build faster ternary expression
          let expression;
          const ternary = t.conditionalExpression(
            t.binaryExpression(">", leftArg, rightArg),
            leftArg,
            rightArg
          );

          // cache previous max comparisons for later reuse
          if (isNested && !isLast) {
            expression = t.assignmentExpression("=", result, ternary);
          }

          // apply cached result from previous run
          if (lastTernary) {
            ternary.consequent = lastResult;
          }

          lastTernary = ternary;
          lastIntermmediate = expression || ternary;
          lastResult = result;
        }

        const replacement = [lastIntermmediate];

        // put declarations before micro optimization
        if (declarations.length) {
          replacement.unshift(cache);
        }

        path.replaceWithMultiple(replacement);
      }
    }
  };
}
```

**Comment by AndyOGo** [comment]
https://github.com/babel/babylon/blob/master/ast/spec.md#memberexpression
